(function(){
  'use strict';
  function loadResponsiveStyles(){if(document.querySelector('link[data-responsive-styles]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='responsive.css';l.dataset.responsiveStyles='true';document.head.appendChild(l)}
  function replaceCsvText(){if(!document.body)return;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];let n;while((n=w.nextNode()))if(n.nodeValue&&n.nodeValue.includes('CSV'))nodes.push(n);nodes.forEach(x=>x.nodeValue=x.nodeValue.replaceAll('CSV','Excel'))}
  function injectRestore(){if(document.getElementById('restoreBackupBtn'))return;const backup=document.getElementById('backupBtn');if(!backup)return;const btn=document.createElement('button');btn.id='restoreBackupBtn';btn.type='button';btn.className=backup.className;btn.textContent='استعادة نسخة احتياطية';btn.addEventListener('click',async()=>{try{await window.gymAPI.restoreBackup()}catch(e){alert(e?.message||e)}});backup.insertAdjacentElement('afterend',btn)}
  function injectSettingsPages(){
    if(document.getElementById('settingsPageNav'))return;
    const settings=document.getElementById('settings'),layout=settings?.querySelector('.settings-layout'),title=settings?.querySelector('.page-title');if(!settings||!layout||!title)return;
    const nav=document.createElement('div');nav.id='settingsPageNav';nav.className='settings-subnav';nav.innerHTML=`<button type="button" class="settings-subnav-btn active" data-settings-target="settingsGeneralPage"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.3.9a7 7 0 0 0-1.7-1L14.5 3h-5L9 6a7 7 0 0 0-1.7 1L5 6.1 3 9.5 5.1 11a7 7 0 0 0 0 2L3 14.5 5 18l2.3-1a7 7 0 0 0 1.7 1l.5 3h5l.5-3a7 7 0 0 0 1.7-1l2.3 1 2-3.5-2.1-1.5a7 7 0 0 0 .1-1z"/></svg><span><b>إعدادات النظام والخطط</b><small>الخطط والأسعار والنسخ الاحتياطي والتصدير</small></span></button><button type="button" class="settings-subnav-btn" data-settings-target="settingsLoginPage"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v2"/></svg><span><b>بيانات تسجيل الدخول</b><small>تغيير اسم المستخدم وكلمة المرور</small></span></button>`;title.insertAdjacentElement('afterend',nav);
    const general=document.createElement('div');general.id='settingsGeneralPage';general.className='settings-subpage active';layout.parentNode.insertBefore(general,layout);general.appendChild(layout);
    const login=document.createElement('div');login.id='settingsLoginPage';login.className='settings-subpage';login.innerHTML=`<div class="auth-page-card"><div class="auth-page-head"><div class="auth-page-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v2"/></svg></div><div><h3>بيانات تسجيل الدخول</h3><p>يمكنك تغيير اسم المستخدم أو كلمة المرور الخاصة بفتح البرنامج.</p></div></div><form id="authSettingsForm" class="auth-form"><div class="form-grid"><div class="field"><label>اسم المستخدم</label><input id="authNewUsername" autocomplete="username" required></div><div class="field"><label>كلمة المرور الحالية *</label><input id="authCurrentPassword" type="password" required></div><div class="field"><label>كلمة المرور الجديدة</label><input id="authNewPassword" type="password" placeholder="اتركها فارغة للإبقاء على الحالية"></div><div class="field"><label>تأكيد كلمة المرور الجديدة</label><input id="authConfirmPassword" type="password" placeholder="أعد كتابة كلمة المرور الجديدة"></div></div><div class="auth-form-actions"><button class="btn btn-primary" type="submit">حفظ بيانات الدخول</button><span id="authSettingsMessage"></span></div></form></div>`;general.insertAdjacentElement('afterend',login);
    const buttons=[...nav.querySelectorAll('[data-settings-target]')];async function show(id){buttons.forEach(b=>b.classList.toggle('active',b.dataset.settingsTarget===id));[general,login].forEach(p=>p.classList.toggle('active',p.id===id));if(id==='settingsLoginPage'){try{const r=await window.gymAPI.authInfo();if(r?.ok)login.querySelector('#authNewUsername').value=r.data?.username||''}catch{}}}buttons.forEach(b=>b.addEventListener('click',()=>show(b.dataset.settingsTarget)));
    const u=login.querySelector('#authNewUsername'),c=login.querySelector('#authCurrentPassword'),p=login.querySelector('#authNewPassword'),pc=login.querySelector('#authConfirmPassword'),m=login.querySelector('#authSettingsMessage');login.querySelector('#authSettingsForm').addEventListener('submit',async e=>{e.preventDefault();m.textContent='';m.className='';if(p.value!==pc.value){m.className='auth-msg error';m.textContent='تأكيد كلمة المرور الجديدة غير مطابق';return}try{const r=await window.gymAPI.changeCredentials({currentPassword:c.value,newUsername:u.value.trim(),newPassword:p.value});if(!r?.ok)throw new Error(r?.error||'تعذر حفظ بيانات الدخول');u.value=r.data?.username||u.value;c.value='';p.value='';pc.value='';m.className='auth-msg success';m.textContent='تم حفظ بيانات الدخول بنجاح'}catch(err){m.className='auth-msg error';m.textContent=err?.message||'تعذر حفظ بيانات الدخول'}});
  }
  window.addEventListener('DOMContentLoaded',()=>{loadResponsiveStyles();replaceCsvText();setTimeout(()=>{injectSettingsPages();injectRestore();replaceCsvText()},0);setTimeout(()=>{injectSettingsPages();injectRestore();replaceCsvText()},600);new MutationObserver(()=>{replaceCsvText();injectRestore()}).observe(document.documentElement,{childList:true,subtree:true,characterData:true})});
})();
