'use strict';
const api=window.gymAPI;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let state={plans:[],allPlans:[],settings:{currency:'جنيه'},trainees:[],dashboard:{},selected:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtMoney=n=>`${Number(n||0).toLocaleString('ar-EG',{maximumFractionDigits:2})} ${state.settings.currency||'جنيه'}`;
const fmtDate=v=>v?new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium'}).format(new Date(v)):'—';
const dateInput=v=>v?new Date(v).toISOString().slice(0,10):'';
const unwrap=r=>{if(!r?.ok)throw new Error(r?.error||'حدث خطأ غير متوقع');return r.data};
const icon=id=>`<svg><use href="#${id}"/></svg>`;
function notify(msg,error=false){const t=$('#toast');t.textContent=msg;t.classList.toggle('error',error);t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),3000)}
async function safe(fn){try{return await fn()}catch(e){notify(e.message||String(e),true);throw e}}
function statusMeta(s){if(s==='active')return['نشط','badge-active'];if(s==='expiring')return['ينتهي قريبًا','badge-expiring'];if(s==='expired')return['منتهي','badge-expired'];return['بدون اشتراك','badge-archived']}
function addMonthsInclusive(startValue,months){const s=new Date(`${startValue}T00:00:00`),day=s.getDate(),d=new Date(s.getFullYear(),s.getMonth()+Math.max(1,Number(months)||1),day);if(d.getDate()!==day)d.setDate(0);d.setDate(d.getDate()-1);return d}
function initials(name){return String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('')}

async function init(){await safe(async()=>{const x=unwrap(await api.bootstrap());state={...state,...x};$('#sideGymName').textContent=state.settings.gymName||'كابتن مصطفى الريدي';fillPlanSelects();fillSettings();renderDashboard();renderTrainees(state.trainees);renderReminders(state.reminders);$('#addStart').value=new Date().toISOString().slice(0,10);calcAddSummary();bindEvents();window.__GYM_UI_READY__=true;window.__GYM_UI_FEATURES__={views:$$('.view').length,nav:$$('.nav-btn').length,buttons:$$('button').length,hasCsv:!!$('#topExport'),hasPlans:!!$('#newPlanForm'),hasEdit:true}})}
function bindEvents(){
  $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));$$('.modal-back').forEach(b=>b.addEventListener('click',e=>{if(e.target===b)b.classList.remove('show')}));
  $('#globalSearch').addEventListener('input',debounce(()=>{showView('trainees');loadTrainees()},180));['filterStatus','filterPlan','filterArchive','filterOwing'].forEach(id=>$('#'+id).addEventListener('change',loadTrainees));
  $('#addPlan').addEventListener('change',calcAddSummary);$('#addMonths').addEventListener('input',calcAddSummary);$('#addPaid').addEventListener('input',calcAddSummary);$('#addStart').addEventListener('change',calcAddSummary);
  $('#addForm').addEventListener('submit',submitAdd);$('#settingsForm').addEventListener('submit',saveSettings);$('#newPlanForm').addEventListener('submit',addPlan);
  $('#refreshDashboard').onclick=refreshAll;$('#refreshReminders').onclick=loadReminders;['topExport','quickExport','exportTrainees','settingsExport'].forEach(id=>$('#'+id).onclick=exportCsv);$('#backupBtn').onclick=backup;$('#dataFolderBtn').onclick=openDataFolder;
}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='trainees')loadTrainees();if(id==='dashboard')loadDashboard();if(id==='reminders')loadReminders();if(id==='settings')refreshPlans()}

function fillPlanSelects(){const opts=state.plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ${fmtMoney(p.monthlyPrice)}</option>`).join('');$('#addPlan').innerHTML=opts;$('#filterPlan').innerHTML='<option value="all">كل الخطط</option>'+state.plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');renderPlanSettings()}
function fillSettings(){const f=$('#settingsForm');['gymName','currency','reminderDays','reminderTemplate'].forEach(k=>{if(f.elements[k])f.elements[k].value=state.settings[k]??''})}
function statCard(label,value,note,tone,accent,iconId){return`<div class="stat-card" style="--tone:${tone};--accent:${accent}"><div class="stat-icon">${icon(iconId)}</div><span class="stat-label">${label}</span><div class="stat-value">${value}</div><div class="stat-note">${note}</div></div>`}
function renderDashboard(){const d=state.dashboard||{};$('#stats').innerHTML=[statCard('إجمالي المتدربين',Number(d.total||0).toLocaleString('ar-EG'),'الحاليون غير المؤرشفين','#158c63','#e8f8f0','i-users'),statCard('الاشتراكات النشطة',Number(d.active||0).toLocaleString('ar-EG'),'نشط لأكثر من يومين','#237bd4','#eaf2fc','i-home'),statCard('تنتهي خلال يومين',Number(d.expiring||0).toLocaleString('ar-EG'),'تحتاج متابعة','#bd770c','#fff3dd','i-bell'),statCard('الاشتراكات المنتهية',Number(d.expired||0).toLocaleString('ar-EG'),'بحاجة إلى تجديد','#cc4350','#ffebed','i-refresh'),statCard('المحصل هذا الشهر',fmtMoney(d.paidMonth),'دفعات الشهر الحالي','#158c63','#e8f8f0','i-money'),statCard('إجمالي المدفوع',fmtMoney(d.totalPaid),'كل الدفعات المسجلة','#237bd4','#eaf2fc','i-money'),statCard('إجمالي المتبقي',fmtMoney(d.remaining),'على الاشتراكات الحالية','#c26822','#fff1e8','i-money'),statCard('نسبة التحصيل',`${Number(d.collectionRate||0).toLocaleString('ar-EG')}٪`,'من قيمة الاشتراكات الحالية','#7257d2','#f0edfc','i-money')].join('');
  const rp=d.recentPayments||[];$('#recentPayments').innerHTML=rp.length?rp.map(p=>`<div class="list-row"><div><div class="list-title">${esc(p.name)}</div><div class="list-sub">${fmtDate(p.paymentDate)} · ${esc(p.method)}</div></div><div class="money-positive">${fmtMoney(p.amount)}</div></div>`).join(''):'<div class="empty">لا توجد دفعات مسجلة بعد</div>';
  const counts=d.planCounts||{},max=Math.max(1,...Object.values(counts));$('#planReport').innerHTML=Object.keys(counts).length?Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="bar-row"><span>${esc(n)}</span><div class="bar-bg"><div class="bar-fill" style="width:${Math.round(c/max*100)}%"></div></div><b>${Number(c).toLocaleString('ar-EG')}</b></div>`).join(''):'<div class="empty">لا توجد بيانات كافية</div>';
  const ex=d.expiringSoon||[];$('#expiringList').innerHTML=ex.length?ex.map(t=>`<div class="list-row"><div><div class="list-title">${esc(t.name)}</div><div class="list-sub">${esc(t.subscription.planName)} · ينتهي ${fmtDate(t.subscription.endDate)}</div></div><button class="btn btn-sm btn-warn" onclick="openProfile('${t.id}')">فتح الملف</button></div>`).join(''):'<div class="empty">لا توجد اشتراكات تنتهي خلال يومين</div>';
  $('#collectionReport').innerHTML=`<div style="text-align:center;padding:8px"><div class="progress-ring">${Number(d.collectionRate||0).toLocaleString('ar-EG')}٪</div><div class="muted" style="font-size:10px;margin-top:5px">نسبة التحصيل الحالية</div></div><div class="divider"></div><div class="list-row"><div class="list-title">قيمة الاشتراكات الحالية</div><b>${fmtMoney(d.currentValue)}</b></div><div class="list-row"><div class="list-title">المتبقي للتحصيل</div><b class="money-due">${fmtMoney(d.remaining)}</b></div>`}
async function loadDashboard(){await safe(async()=>{state.dashboard=unwrap(await api.dashboard());renderDashboard()})}
async function refreshAll(){await safe(async()=>{const x=unwrap(await api.bootstrap());state={...state,...x};fillPlanSelects();fillSettings();renderDashboard();renderTrainees(x.trainees);renderReminders(x.reminders);notify('تم تحديث جميع البيانات')})}

async function loadTrainees(){await safe(async()=>{const filters={search:$('#globalSearch').value.trim(),status:$('#filterStatus').value,planId:$('#filterPlan').value,archived:$('#filterArchive').value==='true',owing:$('#filterOwing').checked};state.trainees=unwrap(await api.list(filters));renderTrainees(state.trainees)})}
function renderTrainees(rows){$('#traineeCount').textContent=`${rows.length.toLocaleString('ar-EG')} متدرب`;if(!rows.length){$('#traineeTable').innerHTML='<div class="empty">لا توجد نتائج مطابقة</div>';return}$('#traineeTable').innerHTML=`<table><thead><tr><th>المتدرب</th><th>الموبايل</th><th>الخطة</th><th>الفترة</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>${rows.map(t=>{const s=t.subscription,m=statusMeta(t.archived?'archived':s?.status);return`<tr><td><div class="person"><span class="avatar">${esc(initials(t.name))}</span><div><b>${esc(t.name)}</b><div class="list-sub">${esc(t.country)}</div></div></div></td><td>${esc(t.phone)}</td><td>${esc(s?.planName||'—')}</td><td>${s?`${fmtDate(s.startDate)}<div class="list-sub">حتى ${fmtDate(s.endDate)}</div>`:'—'}</td><td>${fmtMoney(s?.totalAmount)}</td><td class="money-positive">${fmtMoney(s?.paid)}</td><td class="money-due">${fmtMoney(s?.remaining)}</td><td><span class="badge ${m[1]}">${m[0]}</span></td><td><div class="actions"><button class="icon-btn" title="فتح الملف" onclick="openProfile('${t.id}')">${icon('i-eye')}</button><button class="icon-btn" title="تعديل" onclick="openEditTrainee('${t.id}')">${icon('i-edit')}</button>${t.archived?`<button class="icon-btn" title="استعادة" onclick="archiveTrainee('${t.id}',false)">${icon('i-refresh')}</button>`:`<button class="icon-btn" title="أرشفة" onclick="archiveTrainee('${t.id}',true)">${icon('i-archive')}</button>`}</div></td></tr>`}).join('')}</tbody></table>`}

async function openProfile(id){await safe(async()=>{state.selected=unwrap(await api.get(id));renderProfile();$('#profileBack').classList.add('show')})}
function renderProfile(){const t=state.selected,s=t.subscription,m=statusMeta(t.archived?'archived':s?.status);$('#profileBody').innerHTML=`<div class="profile-hero"><div class="profile-id"><div class="profile-avatar">${esc(initials(t.name))}</div><div><h2>${esc(t.name)}</h2><p>${esc(t.phone)} · ${esc(t.country)}</p><div style="margin-top:7px"><span class="badge ${m[1]}">${m[0]}</span></div></div></div><div class="profile-actions"><button class="btn btn-sm btn-secondary" onclick="openEditTrainee('${t.id}')">${icon('i-edit')} تعديل البيانات</button><button class="btn btn-sm btn-secondary" onclick="openEditSubscription('${t.id}')">تعديل الاشتراك</button><button class="btn btn-sm btn-primary" onclick="openPayment('${t.id}')">تسجيل دفعة</button><button class="btn btn-sm btn-soft" onclick="openRenew('${t.id}')">تجديد</button></div></div><div class="info-grid"><div class="info-box"><span>الخطة الحالية</span><b>${esc(s?.planName||'—')}</b></div><div class="info-box"><span>نهاية الاشتراك</span><b>${fmtDate(s?.endDate)}</b></div><div class="info-box"><span>الإجمالي</span><b>${fmtMoney(s?.totalAmount)}</b></div><div class="info-box"><span>المدفوع / المتبقي</span><b>${fmtMoney(s?.paid)} / <span class="money-due">${fmtMoney(s?.remaining)}</span></b></div></div><div class="info-grid"><div class="info-box"><span>رقم واتساب</span><b>${esc(t.normalizedPhone)}</b></div><div class="info-box"><span>عدد الأشهر</span><b>${s?.months||'—'}</b></div><div class="info-box"><span>الأيام المتبقية</span><b>${s?Number(s.daysRemaining).toLocaleString('ar-EG'):'—'}</b></div><div class="info-box"><span>ملاحظات</span><b>${esc(t.notes||'لا توجد')}</b></div></div><div class="profile-actions"><button class="btn btn-sm btn-soft" onclick="sendWhatsApp('${t.id}')">واتساب</button>${t.archived?`<button class="btn btn-sm btn-secondary" onclick="archiveTrainee('${t.id}',false)">استعادة من الأرشيف</button>`:`<button class="btn btn-sm btn-warn" onclick="archiveTrainee('${t.id}',true)">أرشفة</button>`}<button class="btn btn-sm btn-danger" onclick="deleteTrainee('${t.id}')">حذف نهائي</button></div><div class="tabs"><button class="tab-btn active" onclick="switchTab(this,'subs')">الاشتراكات</button><button class="tab-btn" onclick="switchTab(this,'payments')">الدفعات</button><button class="tab-btn" onclick="switchTab(this,'remindersTab')">التنبيهات</button></div><div class="tab-pane active" id="subs">${renderSubs(t.subscriptions)}</div><div class="tab-pane" id="payments">${renderPayments(t.payments)}</div><div class="tab-pane" id="remindersTab">${renderReminderHistory(t.reminders)}</div>`}
function renderSubs(rows){return rows?.length?rows.map(s=>`<div class="history-row"><div><b>${esc(s.planName)}</b><div class="list-sub">${fmtDate(s.startDate)} → ${fmtDate(s.endDate)} · ${s.months} شهر</div></div><div><b>${fmtMoney(s.totalAmount)}</b><div class="list-sub">مدفوع ${fmtMoney(s.paid)}</div></div></div>`).join(''):'<div class="empty">لا يوجد سجل اشتراكات</div>'}
function renderPayments(rows){return rows?.length?rows.map(p=>`<div class="history-row"><div><b>${esc(p.method)}</b><div class="list-sub">${fmtDate(p.paymentDate)}${p.note?' · '+esc(p.note):''}</div></div><b class="money-positive">${fmtMoney(p.amount)}</b></div>`).join(''):'<div class="empty">لا توجد دفعات</div>'}
function renderReminderHistory(rows){return rows?.length?rows.map(r=>`<div class="history-row"><div><b>${r.status==='sent'?'تم الإرسال':'معلق'}</b><div class="list-sub">${fmtDate(r.scheduledDate)} · ${esc(r.message)}</div></div></div>`).join(''):'<div class="empty">لا توجد تنبيهات</div>'}
function switchTab(btn,id){btn.parentElement.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');btn.closest('.modal-body').querySelectorAll('.tab-pane').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function closeModal(id){$('#'+id).classList.remove('show')}
function openForm(title,html,onSubmit){$('#formTitle').textContent=title;$('#formBody').innerHTML=html;$('#formBack').classList.add('show');const form=$('#formBody form');if(form)form.onsubmit=async e=>{e.preventDefault();await safe(()=>onSubmit(form));closeModal('formBack')}}

async function openEditTrainee(id){const t=state.selected?.id===id?state.selected:unwrap(await api.get(id));openForm('تعديل بيانات المتدرب',`<form><div class="form-grid"><div class="field"><label>الاسم</label><input name="name" required value="${esc(t.name)}"></div><div class="field"><label>البلد</label><input name="country" value="${esc(t.country)}"></div><div class="field"><label>كود الدولة</label><input name="countryCode" value="${esc(t.countryCode)}"></div><div class="field"><label>رقم الموبايل</label><input name="phone" required value="${esc(t.phone)}"></div><div class="field full"><label>ملاحظات</label><textarea name="notes" rows="4">${esc(t.notes)}</textarea></div><div class="field full"><label class="check-line"><input type="checkbox" name="whatsappEnabled" ${t.whatsappEnabled?'checked':''}> تفعيل واتساب</label></div></div><button class="btn btn-primary mt">حفظ التعديلات</button></form>`,async f=>{state.selected=unwrap(await api.update(id,{name:f.name.value,country:f.country.value,countryCode:f.countryCode.value,phone:f.phone.value,notes:f.notes.value,whatsappEnabled:f.whatsappEnabled.checked}));await refreshAfterChange('تم تعديل بيانات المتدرب')})}
async function openEditSubscription(id){const t=state.selected?.id===id?state.selected:unwrap(await api.get(id)),s=t.subscription;if(!s)return notify('لا يوجد اشتراك حالي لتعديله',true);openForm('تعديل الاشتراك الحالي',`<form><div class="form-grid"><div class="field full"><label>الخطة</label><select name="planId">${state.plans.map(p=>`<option value="${p.id}" ${p.id===s.planId?'selected':''}>${esc(p.name)} — ${fmtMoney(p.monthlyPrice)}</option>`).join('')}</select></div><div class="field"><label>عدد الأشهر</label><input type="number" min="1" name="months" value="${s.months}"></div><div class="field"><label>تاريخ البداية</label><input type="date" name="startDate" value="${dateInput(s.startDate)}"></div></div><p class="muted">سيتم إعادة حساب السعر وتاريخ النهاية تلقائيًا، مع الاحتفاظ بجميع الدفعات المسجلة.</p><button class="btn btn-primary mt">حفظ تعديل الاشتراك</button></form>`,async f=>{state.selected=unwrap(await api.updateSubscription(id,{planId:f.planId.value,months:Number(f.months.value),startDate:f.startDate.value}));await refreshAfterChange('تم تعديل الاشتراك')})}
async function openPayment(id){const t=state.selected?.id===id?state.selected:unwrap(await api.get(id)),s=t.subscription;if(!s||s.remaining<=0)return notify('لا يوجد مبلغ متبقي على الاشتراك',true);openForm('تسجيل دفعة جديدة',`<form><div class="field"><label>المتبقي الحالي</label><input value="${fmtMoney(s.remaining)}" disabled></div><div class="field mt"><label>قيمة الدفعة</label><input type="number" name="amount" min="0.01" max="${s.remaining}" step="0.01" required></div><div class="field mt"><label>طريقة الدفع</label><select name="method"><option>نقدي</option><option>InstaPay</option><option>Vodafone Cash</option><option>تحويل بنكي</option><option>أخرى</option></select></div><div class="field mt"><label>ملاحظة</label><input name="note"></div><button class="btn btn-primary mt">تسجيل الدفعة</button></form>`,async f=>{state.selected=unwrap(await api.payment(id,s.id,Number(f.amount.value),f.method.value,f.note.value));await refreshAfterChange('تم تسجيل الدفعة')})}
async function openRenew(id){const t=state.selected?.id===id?state.selected:unwrap(await api.get(id));openForm('تجديد الاشتراك',`<form><div class="form-grid"><div class="field full"><label>الخطة</label><select name="planId">${state.plans.map(p=>`<option value="${p.id}">${esc(p.name)} — ${fmtMoney(p.monthlyPrice)}</option>`).join('')}</select></div><div class="field"><label>عدد الأشهر</label><input type="number" min="1" name="months" value="1"></div><div class="field"><label>تاريخ البداية</label><input type="date" name="startDate" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>دفعة أولى</label><input type="number" min="0" step="0.01" name="paid" value="0"></div><div class="field"><label>طريقة الدفع</label><select name="method"><option>نقدي</option><option>InstaPay</option><option>Vodafone Cash</option><option>تحويل بنكي</option></select></div></div><button class="btn btn-primary mt">إنشاء اشتراك جديد</button></form>`,async f=>{state.selected=unwrap(await api.renew(id,{planId:f.planId.value,months:Number(f.months.value),startDate:f.startDate.value,paid:Number(f.paid.value),method:f.method.value}));await refreshAfterChange('تم تجديد الاشتراك')})}
async function refreshAfterChange(msg){await refreshAll();if(state.selected?.id){state.selected=unwrap(await api.get(state.selected.id));renderProfile()}notify(msg)}
async function archiveTrainee(id,value){if(value&&!confirm('هل تريد أرشفة هذا المتدرب؟'))return;await safe(async()=>{unwrap(await api.archive(id,value));if(state.selected?.id===id)closeModal('profileBack');await refreshAll();notify(value?'تم نقل المتدرب إلى الأرشيف':'تمت استعادة المتدرب')})}
async function deleteTrainee(id){if(!confirm('حذف نهائي: سيتم حذف المتدرب وكل اشتراكاته ودفعاته. هل أنت متأكد؟'))return;await safe(async()=>{unwrap(await api.delete(id));closeModal('profileBack');await refreshAll();notify('تم الحذف النهائي')})}
async function sendWhatsApp(id){const t=state.selected?.id===id?state.selected:unwrap(await api.get(id));const msg=`أهلاً ${t.name}، تحيات ${state.settings.gymName||'الجيم'}.`;await safe(async()=>{unwrap(await api.whatsapp(t.normalizedPhone,msg));notify('تم فتح واتساب')})}

function calcAddSummary(){const p=state.plans.find(x=>x.id===$('#addPlan').value),months=Math.max(1,Number($('#addMonths').value)||1),paid=Math.max(0,Number($('#addPaid').value)||0),total=(p?.monthlyPrice||0)*months,start=$('#addStart').value,end=start?addMonthsInclusive(start,months):null;$('#addSummary').innerHTML=`<div class="summary-item"><span>سعر الشهر</span><b>${fmtMoney(p?.monthlyPrice)}</b></div><div class="summary-item"><span>الإجمالي</span><b>${fmtMoney(total)}</b></div><div class="summary-item"><span>المدفوع</span><b>${fmtMoney(paid)}</b></div><div class="summary-item"><span>المتبقي</span><b>${fmtMoney(Math.max(0,total-paid))}</b></div><div class="summary-item"><span>تاريخ الانتهاء</span><b>${end?fmtDate(end):'—'}</b></div>`}
async function submitAdd(e){e.preventDefault();const f=e.currentTarget;await safe(async()=>{const t=unwrap(await api.add({name:f.name.value,country:f.country.value,countryCode:f.countryCode.value,phone:f.phone.value,planId:f.planId.value,months:Number(f.months.value),startDate:f.startDate.value,paid:Number(f.paid.value),method:f.method.value,notes:f.notes.value,whatsappEnabled:f.whatsappEnabled.checked}));f.reset();f.country.value='مصر';f.countryCode.value='+20';f.months.value=1;f.paid.value=0;f.whatsappEnabled.checked=true;$('#addStart').value=new Date().toISOString().slice(0,10);calcAddSummary();await refreshAll();notify('تم إضافة المتدرب بنجاح');openProfile(t.id)})}

async function loadReminders(){await safe(async()=>{state.reminders=unwrap(await api.reminders());renderReminders(state.reminders)})}
function renderReminders(rows){$('#reminderList').innerHTML=rows?.length?rows.map(r=>`<div class="list-row"><div><div class="list-title">${esc(r.name)}</div><div class="list-sub">${esc(r.phone)} · مستحق ${fmtDate(r.scheduledDate)}<br>${esc(r.message)}</div></div><button class="btn btn-sm btn-primary" onclick="sendReminder('${r.id}','${r.traineeId}')">إرسال واتساب</button></div>`).join(''):'<div class="empty">لا توجد تنبيهات مستحقة الآن</div>'}
async function sendReminder(reminderId,traineeId){const r=state.reminders.find(x=>x.id===reminderId);if(!r)return;await safe(async()=>{unwrap(await api.whatsapp(r.phone,r.message,r.id));await loadReminders();notify('تم فتح واتساب وتسجيل التنبيه')})}

function renderPlanSettings(){const rows=state.allPlans||state.plans;$('#planSettings').innerHTML=rows.map(p=>`<div class="plan-row ${p.active?'':'inactive'}" data-plan="${p.id}"><input class="plan-name" value="${esc(p.name)}"><input class="plan-price" type="number" min="1" step="0.01" value="${p.monthlyPrice}"><div class="actions"><button class="icon-btn" title="حفظ" onclick="savePlan('${p.id}')">${icon('i-edit')}</button><button class="btn btn-sm ${p.active?'btn-warn':'btn-soft'}" onclick="togglePlan('${p.id}',${!p.active})">${p.active?'إيقاف':'تفعيل'}</button></div></div>`).join('')||'<div class="empty">لا توجد خطط</div>'}
async function refreshPlans(){await safe(async()=>{state.plans=unwrap(await api.plans(false));state.allPlans=unwrap(await api.plans(true));fillPlanSelects()})}
async function addPlan(e){e.preventDefault();const f=e.currentTarget;await safe(async()=>{unwrap(await api.createPlan({name:f.name.value,monthlyPrice:Number(f.monthlyPrice.value)}));f.reset();await refreshPlans();notify('تمت إضافة خطة الاشتراك الجديدة')})}
async function savePlan(id){const row=document.querySelector(`[data-plan="${CSS.escape(id)}"]`);await safe(async()=>{unwrap(await api.updatePlan(id,{name:row.querySelector('.plan-name').value,monthlyPrice:Number(row.querySelector('.plan-price').value)}));await refreshPlans();await loadDashboard();notify('تم حفظ بيانات الخطة')})}
async function togglePlan(id,value){await safe(async()=>{unwrap(await api.setPlanActive(id,value));await refreshPlans();notify(value?'تم تفعيل الخطة':'تم إيقاف الخطة مع الاحتفاظ بتاريخها')})}
async function saveSettings(e){e.preventDefault();const f=e.currentTarget;await safe(async()=>{state.settings=unwrap(await api.saveSettings({gymName:f.gymName.value,currency:f.currency.value,reminderDays:f.reminderDays.value,reminderTemplate:f.reminderTemplate.value}));$('#sideGymName').textContent=state.settings.gymName;fillPlanSelects();renderDashboard();notify('تم حفظ الإعدادات')})}
async function exportCsv(){await safe(async()=>{const p=unwrap(await api.exportCsv());if(p)notify('تم تصدير بيانات المتدربين إلى CSV')})}
async function backup(){await safe(async()=>{const p=unwrap(await api.backup());if(p)notify('تم إنشاء النسخة الاحتياطية')})}
async function openDataFolder(){await safe(async()=>{unwrap(await api.openDataFolder())})}

Object.assign(window,{openProfile,openEditTrainee,openEditSubscription,openPayment,openRenew,archiveTrainee,deleteTrainee,sendWhatsApp,switchTab,savePlan,togglePlan,sendReminder});
window.addEventListener('DOMContentLoaded',init);
